apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
# Backend ENVIRONMENT SETTINGS Only, no NERXT_PUBLIC who are in "docker" image to be complied with webApp
  pgHost: {{ .Values.pgHost | b64enc }}
  pgPort: {{ .Values.pgPort | b64enc }}
  pgName: {{ .Values.pgName | b64enc }}
  pgUser: {{ .Values.pgUser | b64enc }}
  pgPass: {{ .Values.pgPass | b64enc }}
  pgSslMode: {{ .Values.pgSslMode | b64enc }}

  redisHost: {{ .Values.redisHost | b64enc }}
  redisPort: {{ .Values.redisPort | b64enc }}
  redisPwd: {{ .Values.redisPwd | b64enc }}
  redisDb: {{ .Values.redisDb | b64enc }}

  logLevel: {{ .Values.logLevel | b64enc }}

  jwtSecretKey: {{ .Values.jwtSecretKey | b64enc }}
  seedAdminName: {{ .Values.seedAdminName | b64enc }}
  seedAdminPass: {{ .Values.seedAdminPass | b64enc }}
